name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v2
        with:
          node-version: '>=20.6.0'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm test

      - run: echo "_REV=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # MV2

      - run: rm -rf dist && pnpm build-mv2
      - uses: actions/upload-artifact@v4
        with:
          name: 'stylus-mv2-${{ env._VER }}-${{ env._REV }}'
          path: 'dist/*'
          if-no-files-found: error

      # MV3 chrome

      - run: rm -rf dist && pnpm build-chrome-mv3
      - uses: actions/upload-artifact@v4
        with:
          name: 'stylus-chrome-mv3-${{ env._VER }}-${{ env._REV }}'
          path: 'dist/*'
          if-no-files-found: error
